import type {
  AiInsight,
  Bookmark,
  ChatSuggestion,
  Company,
  Conversation,
  DocumentItem,
  ModelOption,
} from '@/types';

export const MODELS: ModelOption[] = [
  { id: 'gpt-5', label: 'GPT-5', description: 'OpenAI flagship multimodal', vendor: 'OpenAI' },
  { id: 'claude', label: 'Claude', description: 'Anthropic Sonnet — long context', vendor: 'Anthropic' },
  { id: 'deepseek', label: 'DeepSeek', description: 'Cost-efficient reasoning', vendor: 'DeepSeek' },
  { id: 'llama', label: 'Llama', description: 'Open weights, self-hostable', vendor: 'Meta' },
];

export const COMPANIES: Company[] = [
  {
    id: 'tcs',
    name: 'Tata Consultancy Services',
    ticker: 'TCS',
    sector: 'Technology',
    industry: 'IT Services',
    marketCapCr: 1480000,
    description:
      'TCS is India’s largest IT services company, providing consulting-led, cognitive-powered solutions across banking, retail, and life sciences.',
    latestFilingDate: '2025-07-15',
    totalReports: 42,
    color: '#2563EB',
    metrics: {
      revenue: [
        { period: 'Q1 FY24', value: 59381 },
        { period: 'Q2 FY24', value: 60583 },
        { period: 'Q3 FY24', value: 60583 },
        { period: 'Q4 FY24', value: 61237 },
        { period: 'Q1 FY25', value: 62613 },
        { period: 'Q1 FY26', value: 67635 },
      ],
      profit: [
        { period: 'Q1 FY24', value: 11147 },
        { period: 'Q2 FY24', value: 11552 },
        { period: 'Q3 FY24', value: 11598 },
        { period: 'Q4 FY24', value: 12434 },
        { period: 'Q1 FY25', value: 12040 },
        { period: 'Q1 FY26', value: 13043 },
      ],
      eps: [
        { period: 'Q1 FY24', value: 30.4 },
        { period: 'Q2 FY24', value: 31.5 },
        { period: 'Q3 FY24', value: 31.6 },
        { period: 'Q4 FY24', value: 33.8 },
        { period: 'Q1 FY25', value: 33.1 },
        { period: 'Q1 FY26', value: 35.9 },
      ],
      growth: [
        { period: 'Q1 FY24', value: 12.9 },
        { period: 'Q2 FY24', value: 7.6 },
        { period: 'Q3 FY24', value: 4.0 },
        { period: 'Q4 FY24', value: 3.5 },
        { period: 'Q1 FY25', value: 4.4 },
        { period: 'Q1 FY26', value: 11.1 },
      ],
    },
  },
  {
    id: 'infosys',
    name: 'Infosys Limited',
    ticker: 'INFY',
    sector: 'Technology',
    industry: 'IT Services',
    marketCapCr: 780000,
    description:
      'Infosys is a global leader in next-generation digital services and consulting, with FY26 guidance of 3–5% growth in constant currency.',
    latestFilingDate: '2025-07-17',
    totalReports: 38,
    color: '#10B981',
    metrics: {
      revenue: [
        { period: 'Q1 FY24', value: 39358 },
        { period: 'Q2 FY24', value: 40986 },
        { period: 'Q3 FY24', value: 41767 },
        { period: 'Q4 FY24', value: 39390 },
        { period: 'Q1 FY25', value: 39310 },
        { period: 'Q1 FY26', value: 41665 },
      ],
      profit: [
        { period: 'Q1 FY24', value: 6064 },
        { period: 'Q2 FY24', value: 6421 },
        { period: 'Q3 FY24', value: 6706 },
        { period: 'Q4 FY24', value: 7969 },
        { period: 'Q1 FY25', value: 6369 },
        { period: 'Q1 FY26', value: 7002 },
      ],
      eps: [
        { period: 'Q1 FY24', value: 14.8 },
        { period: 'Q2 FY24', value: 15.6 },
        { period: 'Q3 FY24', value: 16.1 },
        { period: 'Q4 FY24', value: 19.0 },
        { period: 'Q1 FY25', value: 15.4 },
        { period: 'Q1 FY26', value: 16.9 },
      ],
      growth: [
        { period: 'Q1 FY24', value: 10.9 },
        { period: 'Q2 FY24', value: 6.7 },
        { period: 'Q3 FY24', value: 1.3 },
        { period: 'Q4 FY24', value: -3.7 },
        { period: 'Q1 FY25', value: 3.1 },
        { period: 'Q1 FY26', value: 7.5 },
      ],
    },
  },
  {
    id: 'reliance',
    name: 'Reliance Industries',
    ticker: 'RELIANCE',
    sector: 'Energy',
    industry: 'Oil, Gas & Petrochemicals',
    marketCapCr: 1950000,
    description:
      'Reliance is India’s largest private-sector company spanning energy, retail, digital services (Jio), and new-energy businesses.',
    latestFilingDate: '2025-04-25',
    totalReports: 56,
    color: '#F59E0B',
    metrics: {
      revenue: [
        { period: 'Q1 FY24', value: 210831 },
        { period: 'Q2 FY24', value: 231886 },
        { period: 'Q3 FY24', value: 224879 },
        { period: 'Q4 FY24', value: 240715 },
        { period: 'Q1 FY25', value: 236217 },
        { period: 'Q1 FY26', value: 249878 },
      ],
      profit: [
        { period: 'Q1 FY24', value: 16183 },
        { period: 'Q2 FY24', value: 17784 },
        { period: 'Q3 FY24', value: 17998 },
        { period: 'Q4 FY24', value: 21143 },
        { period: 'Q1 FY25', value: 16911 },
        { period: 'Q1 FY26', value: 18643 },
      ],
      eps: [
        { period: 'Q1 FY24', value: 23.2 },
        { period: 'Q2 FY24', value: 25.5 },
        { period: 'Q3 FY24', value: 25.8 },
        { period: 'Q4 FY24', value: 30.3 },
        { period: 'Q1 FY25', value: 25.0 },
        { period: 'Q1 FY26', value: 27.5 },
      ],
      growth: [
        { period: 'Q1 FY24', value: 8.1 },
        { period: 'Q2 FY24', value: 9.4 },
        { period: 'Q3 FY24', value: -3.0 },
        { period: 'Q4 FY24', value: 7.1 },
        { period: 'Q1 FY25', value: -1.9 },
        { period: 'Q1 FY26', value: 5.8 },
      ],
    },
  },
  {
    id: 'hdfc',
    name: 'HDFC Bank',
    ticker: 'HDFCBANK',
    sector: 'Finance',
    industry: 'Private Sector Bank',
    marketCapCr: 1320000,
    description:
      'HDFC Bank is India’s largest private-sector bank, offering retail banking, wholesale banking, and treasury products.',
    latestFilingDate: '2025-07-19',
    totalReports: 48,
    color: '#2563EB',
    metrics: {
      revenue: [
        { period: 'Q1 FY24', value: 53450 },
        { period: 'Q2 FY24', value: 56860 },
        { period: 'Q3 FY24', value: 61180 },
        { period: 'Q4 FY24', value: 67190 },
        { period: 'Q1 FY25', value: 60820 },
        { period: 'Q1 FY26', value: 71890 },
      ],
      profit: [
        { period: 'Q1 FY24', value: 14040 },
        { period: 'Q2 FY24', value: 15920 },
        { period: 'Q3 FY24', value: 16200 },
        { period: 'Q4 FY24', value: 17550 },
        { period: 'Q1 FY25', value: 16550 },
        { period: 'Q1 FY26', value: 17860 },
      ],
      eps: [
        { period: 'Q1 FY24', value: 19.5 },
        { period: 'Q2 FY24', value: 22.1 },
        { period: 'Q3 FY24', value: 22.5 },
        { period: 'Q4 FY24', value: 24.3 },
        { period: 'Q1 FY25', value: 23.0 },
        { period: 'Q1 FY26', value: 24.8 },
      ],
      growth: [
        { period: 'Q1 FY24', value: 18.4 },
        { period: 'Q2 FY24', value: 6.3 },
        { period: 'Q3 FY24', value: 7.4 },
        { period: 'Q4 FY24', value: 9.7 },
        { period: 'Q1 FY25', value: -9.5 },
        { period: 'Q1 FY26', value: 18.2 },
      ],
    },
  },
];

export const DOCUMENTS: DocumentItem[] = [
  {
    id: 'tcs-q1-fy26',
    name: 'TCS Q1 FY2026 Earnings Report',
    companyId: 'tcs',
    companyName: 'Tata Consultancy Services',
    type: 'quarterly_report',
    quarter: 'Q1 FY2026',
    year: 2025,
    pageCount: 87,
    sizeMb: 4.2,
    uploadedAt: '2025-07-15T09:30:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    sourceUrl: 'https://investor.tcs.com/investor-q1-fy26',
    starred: true,
  },
  {
    id: 'tcs-annual-fy25',
    name: 'TCS Annual Report FY2025',
    companyId: 'tcs',
    companyName: 'Tata Consultancy Services',
    type: 'annual_report',
    year: 2025,
    pageCount: 312,
    sizeMb: 18.7,
    uploadedAt: '2025-05-10T14:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    sourceUrl: 'https://investor.tcs.com/annual-report-fy25',
  },
  {
    id: 'infosys-q1-fy26',
    name: 'Infosys Q1 FY2026 Results',
    companyId: 'infosys',
    companyName: 'Infosys Limited',
    type: 'quarterly_report',
    quarter: 'Q1 FY2026',
    year: 2025,
    pageCount: 64,
    sizeMb: 3.1,
    uploadedAt: '2025-07-17T11:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    starred: true,
  },
  {
    id: 'infosys-investor-pres',
    name: 'Infosys Investor Presentation FY26',
    companyId: 'infosys',
    companyName: 'Infosys Limited',
    type: 'investor_presentation',
    year: 2025,
    pageCount: 38,
    sizeMb: 2.4,
    uploadedAt: '2025-07-17T11:30:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
  },
  {
    id: 'reliance-annual-fy25',
    name: 'Reliance Annual Report FY2025',
    companyId: 'reliance',
    companyName: 'Reliance Industries',
    type: 'annual_report',
    year: 2025,
    pageCount: 428,
    sizeMb: 27.5,
    uploadedAt: '2025-04-25T16:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    starred: true,
  },
  {
    id: 'reliance-q4-call',
    name: 'Reliance Q4 FY25 Earnings Call Transcript',
    companyId: 'reliance',
    companyName: 'Reliance Industries',
    type: 'earnings_call',
    quarter: 'Q4 FY2025',
    year: 2025,
    pageCount: 22,
    sizeMb: 1.1,
    uploadedAt: '2025-04-25T17:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
  },
  {
    id: 'hdfc-q1-fy26',
    name: 'HDFC Bank Q1 FY2026 Earnings',
    companyId: 'hdfc',
    companyName: 'HDFC Bank',
    type: 'quarterly_report',
    quarter: 'Q1 FY2026',
    year: 2025,
    pageCount: 76,
    sizeMb: 3.8,
    uploadedAt: '2025-07-19T10:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
  },
  {
    id: 'hdfc-prospectus',
    name: 'HDFC Bank Debt Prospectus 2024',
    companyId: 'hdfc',
    companyName: 'HDFC Bank',
    type: 'prospectus',
    year: 2024,
    pageCount: 154,
    sizeMb: 9.3,
    uploadedAt: '2024-09-12T08:00:00Z',
    fileUrl: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
  },
];

function makeConversation(
  id: string,
  title: string,
  companyId: string,
  minutesAgo: number,
  messages: Conversation['messages']
): Conversation {
  const createdAt = new Date(Date.now() - minutesAgo * 60 * 1000).toISOString();
  return {
    id,
    title,
    companyId,
    createdAt,
    updatedAt: createdAt,
    messages,
    messageCount: messages.length,
    pinned: false,
    archived: false,
  };
}

export const CONVERSATIONS: Conversation[] = [
  makeConversation('c-tcs-q1', 'TCS Q1 Analysis', 'tcs', 35, [
    {
      id: 'm1',
      role: 'user',
      content: 'What were TCS quarterly results for Q1 FY2026?',
      createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    {
      id: 'm2',
      role: 'assistant',
      model: 'gpt-5',
      content:
        'TCS reported **Q1 FY2026 revenue of Rs 67,635 crore**, up **11.1% YoY** in reported currency. Key highlights:\n\n| Metric | Q1 FY26 | YoY |\n|---|---|---|\n| Revenue | Rs 67,635 Cr | +11.1% |\n| Net Profit | Rs 13,043 Cr | +8.3% |\n| EPS | Rs 35.9 | +8.5% |\n| Margin | 24.4% | -38 bps |\n\nBook-to-bill stood above 1.1 for the quarter, with strong momentum in BFSI and retail verticals. The total order book reached **$44.1 billion**.',
      createdAt: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
      sources: [
        { id: 's1', title: 'TCS Q1 FY2026 Earnings Report', documentId: 'tcs-q1-fy26', page: 4 },
        { id: 's2', title: 'TCS Q1 FY2026 Earnings Report', documentId: 'tcs-q1-fy26', page: 23 },
      ],
      liked: null,
    },
  ]),
  makeConversation('c-infosys-growth', 'Infosys Growth', 'infosys', 180, [
    {
      id: 'm1',
      role: 'user',
      content: 'Compare Infosys revenue for the last 4 quarters.',
      createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    },
    {
      id: 'm2',
      role: 'assistant',
      model: 'claude',
      content:
        'Here is Infosys revenue across the last four quarters:\n\n| Quarter | Revenue (Rs Cr) |\n|---|---|\n| Q3 FY24 | 41,767 |\n| Q4 FY24 | 39,390 |\n| Q1 FY25 | 39,310 |\n| Q1 FY26 | 41,665 |\n\nThe Q4 FY24 dip reflected seasonal weakness; growth resumed at **+7.5% YoY** in Q1 FY26. Management retained FY26 guidance of 3–5% constant-currency growth.',
      createdAt: new Date(Date.now() - 179 * 60 * 1000).toISOString(),
      sources: [
        { id: 's1', title: 'Infosys Q1 FY2026 Results', documentId: 'infosys-q1-fy26', page: 7 },
      ],
      liked: true,
    },
  ]),
  makeConversation('c-reliance-revenue', 'Reliance Revenue', 'reliance', 1440, [
    {
      id: 'm1',
      role: 'user',
      content: 'What risks were mentioned in the Reliance annual report?',
      createdAt: new Date(Date.now() - 1440 * 60 * 1000).toISOString(),
    },
    {
      id: 'm2',
      role: 'assistant',
      model: 'gpt-5',
      content:
        'The Reliance FY2025 annual report highlighted several risk categories:\n\n1. **Commodity price volatility** — refining and petrochemical margins exposed to crude swings.\n2. **Regulatory environment** — telecom and retail face evolving regulation; Jio tariff actions remain under TRAI review.\n3. **New-energy execution** — solar giga-factory ramp and green hydrogen are capital-intensive with multi-year payback.\n4. **FX exposure** — a significant portion of revenue is USD-linked; INR appreciation compresses reported margins.',
      createdAt: new Date(Date.now() - 1439 * 60 * 1000).toISOString(),
      sources: [
        { id: 's1', title: 'Reliance Annual Report FY2025', documentId: 'reliance-annual-fy25', page: 88 },
        { id: 's2', title: 'Reliance Annual Report FY2025', documentId: 'reliance-annual-fy25', page: 142 },
      ],
      liked: null,
    },
  ]),
];

export const INSIGHTS: AiInsight[] = [
  {
    id: 'i-tcs-rev',
    companyId: 'tcs',
    kind: 'revenue_summary',
    title: 'Revenue Summary',
    summary: 'Q1 FY26 revenue grew 11.1% YoY to Rs 67,635 Cr, the strongest growth in six quarters.',
    details: [
      'BFSI vertical revenue grew 12.4% YoY.',
      'Retail & CPG grew double digits YoY.',
      'North America contributed 47.3% of revenue.',
    ],
    sentiment: 'positive',
    confidence: 0.92,
  },
  {
    id: 'i-tcs-profit',
    companyId: 'tcs',
    kind: 'profit_summary',
    title: 'Profit Summary',
    summary: 'Net profit of Rs 13,043 Cr, up 8.3% YoY; margin compressed 38 bps to 24.4%.',
    details: [
      'EBIT margin stood at 24.4%, impacted by wage hikes.',
      'Effective tax rate 25.4%.',
      'Free cash flow conversion exceeded 100% of net income.',
    ],
    sentiment: 'neutral',
    confidence: 0.88,
  },
  {
    id: 'i-tcs-risks',
    companyId: 'tcs',
    kind: 'key_risks',
    title: 'Key Risks',
    summary: 'Wage inflation and H-1B policy uncertainty are the principal near-term risks.',
    details: [
      'Wage hike cycle may compress margins by 60-80 bps over FY26.',
      'US immigration policy affects 60% of the workforce.',
      'Client discretionary spend in Europe remains soft.',
    ],
    sentiment: 'negative',
    confidence: 0.71,
  },
  {
    id: 'i-tcs-growth',
    companyId: 'tcs',
    kind: 'growth_drivers',
    title: 'Growth Drivers',
    summary: 'Cloud, AI, and deals in BFSI are the durable growth pillars.',
    details: [
      'Order book at $44.1B (book-to-bill >1.1).',
      'AI/GenAI pipeline tripling quarter-on-quarter.',
      'Cloud migration deals in retail vertical.',
    ],
    sentiment: 'positive',
    confidence: 0.86,
  },
  {
    id: 'i-tcs-mgmt',
    companyId: 'tcs',
    kind: 'management_commentary',
    title: 'Management Commentary',
    summary: 'Management expressed cautious optimism, signalling sustained FY26 demand.',
    details: [
      '"Demand environment remains resilient." — CEO',
      'Discretionary spend recovery expected H2 FY26.',
      'Continued investment in AI talent.',
    ],
    sentiment: 'positive',
    confidence: 0.79,
  },
  {
    id: 'i-tcs-bull',
    companyId: 'tcs',
    kind: 'bullish_signals',
    title: 'Bullish Signals',
    summary: 'Strong deal TCV, margin resilience, and balance-sheet strength support a positive stance.',
    details: [
      'Order book at record $44.1B.',
      'Net cash position of Rs 73,400 Cr.',
      'Dividend payout ratio sustained above 70%.',
    ],
    sentiment: 'positive',
    confidence: 0.83,
  },
  {
    id: 'i-tcs-bear',
    companyId: 'tcs',
    kind: 'bearish_signals',
    title: 'Bearish Signals',
    summary: 'Margin compression and visa cost inflation warrant monitoring.',
    details: [
      'EBIT margin down 38 bps YoY.',
      'H-1B visa cost rising.',
      'Slowing Europe growth.',
    ],
    sentiment: 'negative',
    confidence: 0.66,
  },
];

export const SUGGESTIONS: ChatSuggestion[] = [
  { id: 's1', prompt: 'What were TCS quarterly results?', companyId: 'tcs' },
  { id: 's2', prompt: 'Compare Infosys revenue for the last 4 quarters.', companyId: 'infosys' },
  { id: 's3', prompt: 'What risks were mentioned in Reliance annual report?', companyId: 'reliance' },
  { id: 's4', prompt: 'Summarize HDFC Bank Q1 FY26 net interest income.', companyId: 'hdfc' },
  { id: 's5', prompt: 'Which company has the highest EPS growth YoY?', companyId: undefined },
];

export const BOOKMARKS: Bookmark[] = [
  {
    id: 'b1',
    kind: 'document',
    refId: 'tcs-q1-fy26',
    title: 'TCS Q1 FY2026 Earnings Report',
    subtitle: 'Quarterly Report • 87 pages',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'b2',
    kind: 'company',
    refId: 'infosys',
    title: 'Infosys Limited',
    subtitle: 'Technology • IT Services',
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
  },
  {
    id: 'b3',
    kind: 'message',
    refId: 'c-tcs-q1',
    title: 'TCS Q1 Analysis — Assistant response',
    subtitle: 'Revenue, profit, EPS, and margin summary',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
];

export function formatCurrencyCr(value: number): string {
  if (value >= 100000) return `₹${(value / 100000).toFixed(2)}L Cr`;
  return `₹${value.toLocaleString('en-IN')} Cr`;
}
